### PR TITLE
Linting and maintenance

### PR DESCRIPTION
**Pull request by prince-chrismc**
My intention is to improve the maintainability of the code base by adding linting to keep things consistent.
The new `.clang-format` is as close to the original syntax I could get.

- 🔧 adding clang-format for source code
- 🖊️ adding editorconfig for all files (this is supported by the GitHub web UI)
- ⚔️ removed old `vcpkg/`
- 💄 adding a logo _(it was not intentional just happened)_

- [x] CI to enforce clang-format is respected

### CODE REVIEW

**Comment by prince-chrismc** [comment]
@Thalhammer do you mind if I remove the `vcpkg/` folder? the files are available in that repo https://github.com/microsoft/vcpkg/tree/master/ports/jwt-cpp

I do not think we need a copy.

**Comment by Thalhammer** [comment]
> @Thalhammer do you mind if I remove the `vcpkg/` folder? the files are available in that repo https://github.com/microsoft/vcpkg/tree/master/ports/jwt-cpp

Naww I dont care.

**Comment by prince-chrismc** [comment]
Logo Idea

Blend of JWT and C++

logo

**Comment by Thalhammer** [comment]
> Logo Idea

Pretty cool, but I would make the "++" a bit finer (similar to the thickness of the remaining font).

**Review by Thalhammer — APPROVED** [review]

**Pull request merged**
