### PR TITLE
Remove undefined behavior usage

### PR DESCRIPTION
**Pull request by lirik90**
It's possible fix for issue #300

### CODE REVIEW

**Review by Thalhammer — APPROVED** [review]
Seems like a good fix to me

**Comment by prince-chrismc** [comment]
It seems the related test are now failing 

```
[ RUN      ] BaseTest.Base64DecodeURLCaseInsensitive
unknown file: Failure
C++ exception with description "std::bad_alloc" thrown in the test body.
[  FAILED  ]
```

**Comment by lirik90** [comment]
Thanks. I'll check it out and come back with a solution.

**Comment by prince-chrismc** [comment]
Going to mark this as a duplicate of #312 thanks a ton for helping fix the problem

**Pull request closed without merging**
