### PR TITLE
Add Wolfssl support

### PR DESCRIPTION
**Pull request by prince-chrismc**

### CODE REVIEW

**Comment by nCk9** [comment]
Hi, I'm working with jwt-cpp and wanted to know how we can enable wolfssl in place of OpenSSL in jwt-cpp. I also tried looking for some documentation regarding the same, but couldn't find any. 
If we see the `jwt.h` file, it has [these](https://github.com/Thalhammer/jwt-cpp/blob/master/include/jwt-cpp/jwt.h#L15) openSSL files included, do we need to include wolfSSL files in the same way?

What is the correct way of using wolfSSL with jwt-cpp.

**Comment by prince-chrismc** [comment]
Excellent question! There should be more docs (feel free to open a PR if you find an easy recipe 🙏 )

Wolfssl has an OpenSSL compatibility layer which jwt-cpp uses. https://www.wolfssl.com/docs/wolfssl-manual/ch13/

In our CI we just make sure to configure everything as on before building and installing :) no need to mess with the includes

Example how we setup/test wolfssl 
https://github.com/Thalhammer/jwt-cpp/blob/275c750fa1362cebdcbbe92adbe53353c3263a15/.github/actions/install/wolfssl/action.yml#L17

**Comment by nCk9** [comment]
I followed all the steps given [here](https://github.com/Thalhammer/jwt-cpp/blob/275c750fa1362cebdcbbe92adbe53353c3263a15/.github/actions/install/wolfssl/action.yml#L12) manually (removed the openssl directory  from `/usr/include` beforehand) and no messing with the header files in `jwt.h`, but the build fails. It shows this error:
Screenshot from 2022-01-03 17-12-05

Please let me know what am I doing wrong here.

**Comment by prince-chrismc** [comment]
Thanks for working through this with us... we need docs 😱 

You need to let JWT know that you are using wolfssl. try configuring cmake like so

https://github.com/Thalhammer/jwt-cpp/blob/275c750fa1362cebdcbbe92adbe53353c3263a15/.github/workflows/ssl.yml#L117

**Comment by nCk9** [comment]
Hi, thanks a lot for helping me through! I did run it and it did find the wolfSSL, but it shows some error in finding GTest, please have a look.
Screenshot from 2022-01-04 23-22-57

**Comment by prince-chrismc** [comment]
Ahh, disable the tests?

```
cmake . -DJWT_BUILD_TESTS=OFF -DJWT_SSL_LIBRARY:STRING=wolfSSL
```

**Comment by nCk9** [comment]
Hi thanks, that worked!! Now since it will use wolfSSL underneath, it is giving these errors when I run `make`. And this is the very first file that's being built, we have 4-5 more files to go. 
I'm hoping it is because you accommodated the changes required for wolfSSL in the `jwt.h` (script updation), but not in the example files, which still refer to openSSL (correct me if I'm wrong). 
Screenshot from 2022-01-05 09-21-02

**Comment by prince-chrismc** [comment]
Hmm, the error is in `jwt.h` 🤔 which version of wolfssl are you using?

**Comment by nCk9** [comment]
It's 4.8.1, and you can also see this in the second screenshot attached above.

**Comment by nCk9** [comment]
I followed this: https://github.com/Thalhammer/jwt-cpp/blob/275c750fa1362cebdcbbe92adbe53353c3263a15/.github/actions/install/wolfssl/action.yml#L7.

**Comment by nCk9** [comment]
Okay, so I tried it with wolfSSL version 5.0.0 as suggested in the `ssl.yml` file, and the good thing is, it did build but with some warnings. But, I'm more concerned that some executables aren't working as they should (only `./print-claims` works fine). It shows `symbol lookup error`. Please have a look!
Screenshot from 2022-01-05 22-49-37

**Comment by prince-chrismc** [comment]
> It's 4.8.1, and you can also see this in the second screenshot attached above.

Screenshot are compressed so they are a little blurry and hard to read for me sorry I missed that.
Ahh that one never worked, it's left over from my testing https://github.com/Thalhammer/jwt-cpp/pull/171/commits/f291b50c76fdaa95423580fcf3532f2a9c2a20ac. 5.0.0 is the minimum release that works.

> It shows `symbol lookup error`

This is normally because linux can not find the `.so` that it needs to load. The installation might not have been successful (mine updates the system settings)


<details><summary>My install logs snippet</summary>


```
libtool: install: /usr/bin/install -c src/.libs/libwolfssl.so.30.0.0 /usr/local/lib/libwolfssl.so.30.0.0
...
libtool: install: (cd /usr/local/lib && { ln -s -f libwolfssl.so.30.0.0 libwolfssl.so.30 || { rm -f libwolfssl.so.30 && ln -s libwolfssl.so.30.0.0 libwolfssl.so.30; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libwolfssl.so.30.0.0 libwolfssl.so || { rm -f libwolfssl.so && ln -s libwolfssl.so.30.0.0 libwolfssl.so; }; })
libtool: install: /usr/bin/install -c src/.libs/libwolfssl.lai /usr/local/lib/libwolfssl.la
...
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin" ldconfig -n /usr/local/lib
```

</details>

You should try running `ldd` to confirm

```sh
$ ldd -d example/es256k
        linux-vdso.so.1 (0x00007ffec5fed000)
        libasan.so.5 => /lib/x86_64-linux-gnu/libasan.so.5 (0x00007f634e838000)
        libwolfssl.so.30 => /usr/local/lib/libwolfssl.so.30 (0x00007f634e562000)  # Notice crypto here 👍 
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f634e380000)
```

I suspect you'll see something more like this

```sh
$ ldd -d example/es256k
        linux-vdso.so.1 (0x00007ffec5fed000)
        libasan.so.5 => /lib/x86_64-linux-gnu/libasan.so.5 (0x00007f634e838000)
        libwolfssl.so.30 => not found # Bad news 👎  
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f634e380000)
```

What you can try is setting `LD_LIBRARY_PATH` if that is the case. Like this if you are using the default install of wolfssl.

```sh
LD_LIBRARY_PATH="/usr/local/lib" ./es256k
```


Hopefully that helps unstick you :)

**Comment by nCk9** [comment]
Hi, so tried running that, and here's what I got! It does find `libwolfssl.so.30`. But I can't see a `libasan.so.5`, maybe this is the problem. Please have a look.
```py
$ ldd -d es256k 
	linux-vdso.so.1 (0x00007ffcb738c000)
	libwolfssl.so.30 => /usr/local/lib/libwolfssl.so.30 (0x00007f8253b2e000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f8253930000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f82537e1000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f82537c6000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f82535d4000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f82535b1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8253c24000)
undefined symbol: wolfSSL_EC_KEY_free	(./es256k)
undefined symbol: wolfSSL_EVP_MD_CTX_free	(./es256k)
undefined symbol: wolfSSL_ECDSA_SIG_free	(./es256k)
undefined symbol: wolfSSL_BN_free	(./es256k)
undefined symbol: wolfSSL_EVP_sha256	(./es256k)
undefined symbol: wolfSSL_X509_free	(./es256k)
undefined symbol: wolfSSL_BIO_free_all	(./es256k)
undefined symbol: wolfSSL_EVP_PKEY_free	(./es256k)
undefined symbol: wolfSSL_EVP_DigestSignFinal	(./es256k)
undefined symbol: wolfSSL_BIO_new	(./es256k)
undefined symbol: wolfSSL_PEM_write_bio_PUBKEY	(./es256k)
undefined symbol: wolfSSL_BN_bn2bin	(./es256k)
undefined symbol: wolfSSL_EVP_PKEY_get1_EC_KEY	(./es256k)
undefined symbol: wolfSSL_PEM_read_bio_PrivateKey	(./es256k)
undefined symbol: wolfSSL_BN_bin2bn	(./es256k)
undefined symbol: wolfSSL_d2i_ECDSA_SIG	(./es256k)
undefined symbol: wolfSSL_BIO_s_mem	(./es256k)
undefined symbol: wolfSSL_BIO_new_mem_buf	(./es256k)
undefined symbol: wolfSSL_EVP_MD_CTX_new	(./es256k)
undefined symbol: wolfSSL_EVP_PKEY_bits	(./es256k)
undefined symbol: wolfSSL_BN_num_bytes	(./es256k)
undefined symbol: wolfSSL_BIO_get_mem_data	(./es256k)
undefined symbol: wolfSSL_PEM_read_bio_X509	(./es256k)
undefined symbol: wolfSSL_BIO_write	(./es256k)
undefined symbol: wolfSSL_i2d_ECDSA_SIG	(./es256k)
undefined symbol: wolfSSL_X509_get_pubkey	(./es256k)
undefined symbol: wolfSSL_EVP_DigestSignInit	(./es256k)
undefined symbol: wolfSSL_EVP_DigestVerifyFinal	(./es256k)
undefined symbol: wolfSSL_EVP_DigestUpdate	(./es256k)
undefined symbol: wolfSSL_EVP_DigestVerifyInit	(./es256k)
undefined symbol: wolfSSL_PEM_read_bio_PUBKEY	(./es256k)
undefined symbol: wolfSSL_EC_KEY_check_key	(./es256k)
```

And about the photo, you might try clicking on it, it'd expand (works for me:sweat_smile:).
Thanks!!

**Comment by nCk9** [comment]
Hi, got it solved!! It works now. The problem was, as initially, I had the wolfSSL version 4.8.1 installed, which I tried deleting from the `/tmp` directory, but this did not delete the related `.so` files in `/usr/local/lib`. And on top of it, I installed wolfSSL version 5.0.0. This made the compiler confused about which version of files to use while building jwt-cpp. So I cleaned the files and re-built them again with 5.0.0. And it worked.

Thanks a lot for your continuous help!!

**Comment by Thalhammer** [comment]
Glad you two got it sorted out.

> But I can't see a libasan.so.5

This is fine. libasan relates to the "AddressSanitizer" that allows checking C/C++ code for memory related bugs. Its only used if explicitly enabled.

**Comment by prince-chrismc** [comment]
Libasan is because of my local testing unrelated :)

Awesome 🚀  glad it's working :)

**Pull request merged**
