### PR TITLE
Prep for the release of 0.7.0

### PR DESCRIPTION
**Pull request by prince-chrismc**
We've had a a fair bit of stability and with the new round of contributions I'd love to cut a release and keep the changes coming :)

I also prep a draft release https://github.com/Thalhammer/jwt-cpp/releases/tag/untagged-3e7c021ab6f444d1e336 (you might have seen me misclick-- sorry sorry)

### CODE REVIEW

**Comment by Thalhammer** [comment]
Would it make sense to maybe wait for #298 before we do a release ?
It seems to be mostly ready and I am pretty sure the author would be happy to be able to pin to a release tag instead of being force to master for his change.

**Comment by prince-chrismc** [comment]
That's totally reasonable to me!

**Comment by prince-chrismc** [comment]
Having done the work for #307 I think I have changed my mind.

I would rather cut a new release since there's some missing tests and it uses new openssl apis.

WDYT?

**Comment by prince-chrismc** [comment]
@Thalhammer I would like to keep this rolling and make this release, if you have any objections let me know :)

**Comment by Thalhammer** [comment]
> @Thalhammer I would like to keep this rolling and make this release, if you have any objections let me know :)

Nope, looks good to me :)

**Review by Thalhammer — APPROVED** [review]

**Comment by prince-chrismc** [comment]
Would you mind updating the Nuget API key? I suspect it has expired

**Comment by Thalhammer** [comment]
> Would you mind updating the Nuget API key? I suspect it has expired

Done. And yes it was indeed expired. As far as I can tell its not possible to generate one thats valid for more than one year.

**Pull request merged**
