### PR TITLE
Exposing private utilities to helpers for helping with other JOSE related tasks

### PR DESCRIPTION
**Pull request by prince-chrismc**
Implementing a strict OAuth2 workflow is made very easy with this library. I have found myself extracting parts of the code in order to help with code_challenge generationg and JWK/JWKS related tasks.

Making the private utilities a part of the API will help other users of this library.

### CODE REVIEW

**Comment by prince-chrismc** [comment]
CI seems to be having issues today =S

**Comment by prince-chrismc** [comment]
@Thalhammer if you get the chance, can you please take a look at this PR :smile:

**Comment by prince-chrismc** [comment]
Would be you be able to make a new release? Maybe a v0.4.0 since all the CMake changes :heart:

**Comment by Thalhammer** [comment]
Normally changes only to the build system would not be a reason to to a version bump, however as there have been quite a few changes to the headers as well in this and other PRs I dont see a problem with doing a new version.

**Comment by prince-chrismc** [comment]
Thank you so much! As you know it's much easier to track versions then commits

**Pull request merged**
