### PR TITLE
Restore support for GCC-4.8

### LINKED ISSUE #197: build broken on gcc version 4.8.5
**Describe the bug**
gcc4.8.5 does not have full support of C++11, so codecvt will broken the build.
```
#include <codecvt>
```
**How To Reproduce** (Include if Applicable)
When try to build [laoshanxi/app-mesh](https://github.com/laoshanxi/app-mesh)
```
# docker run -ti --rm -v `pwd`:/data laoshanxi/appmesh:build_centos7  bash
# mkdir build; cd build;cmake ..;make
```

**Expected behavior**

**Screenshots**
```
bash-4.2# g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) 
```

**Desktop (please complete the following information):**
 - OS: [centos7]
 - Compiler [gcc]
 - Version [4.8.5]

**Additional context**
For the include, we can use below micro to handle, but I am not sure how to handle the function below:
```
#if __cplusplus > 201103L
#include <codecvt>
#endif

static std::string to_lower_unicode(const std::string& str, const std::locale& loc)
```

**Logs** (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
[ 25%] Built target prometheus
[ 27%] Building CXX object src/cli/CMakeFiles/appc.dir/ArgumentParser.cpp.o
In file included from /data/src/cli/ArgumentParser.cpp:16:0:
/data/src/cli/../common/jwt-cpp/jwt.h: In static member function 'static std::string jwt::verify_ops::insensitive_string_claim<json_traits, in_header>::to_lower_unicode(const string&, const std::locale&)':
/data/src/cli/../common/jwt-cpp/jwt.h:3037:5: error: 'wstring_convert' is not a member of 'std'
     std::wstring_convert<std::codecvt_utf8<wchar_t>, wchar_t> conv;
     ^
/data/src/cli/../common/jwt-cpp/jwt.h:3037:26: error: 'codecvt_utf8' is not a member of 'std'
     std::wstring_convert<std::codecvt_utf8<wchar_t>, wchar_t> conv;
                          ^
/data/src/cli/../common/jwt-cpp/jwt.h:3037:44: error: expected primary-expression before 'wchar_t'
     std::wstring_convert<std::codecvt_utf8<wchar_t>, wchar_t> conv;
                                            ^
/data/src/cli/../common/jwt-cpp/jwt.h:3037:44: error: expected ';' before 'wchar_t'
/data/src/cli/../common/jwt-cpp/jwt.h:3038:17: error: 'conv' was not declared in this scope
     auto wide = conv.from_bytes(str);
                 ^
make[2]: *** [src/cli/CMakeFiles/appc.dir/ArgumentParser.cpp.o] Error 1

```

</details>

### PR DESCRIPTION
**Pull request by prince-chrismc**
closes #197 

***

I originally tried to setup a CentOS 7 docker image to build in but that was just too cumbersome. I did almost get it in https://github.com/prince-chrismc/jwt-cpp/blob/c81a6c998607ba05ea2e3b4a131620dc9eabd14a/.github/workflows/targets.yml
but manually compiler CMake just takes forever... 

I saw GitHub Actions still has Ubuntu 18.04 and I know that had GCC-4.8. But that's also limited to CMake 3.10 (we need 3.12 now). So looked into Ubuntu 20.04 [but that just looked horrible](https://stackoverflow.com/questions/61945439/how-to-install-compiler-g-4-8-5-in-ubuntu-20-04). Again, I also looked at a container but that was the same problem as before.

👇 👇 👇 👇 👇 

I personally really want to move to C++17... 23's feature list was just approved by ISO commitee... it's 5years old and the majority of platforms have complete support. Concepts would be amazing but those only made it in all 3 compilers 11 months ago... 

I'd like to set the minimum at

- gcc-9
- clang-10
- msvc 19.12 (Visual Studio 17 15.5)
- apple-clang 10

### CODE REVIEW

**Comment by prince-chrismc** [comment]
@Thalhammer How do you feel about 0.8.0 being C++17?

**Comment by Thalhammer** [comment]
> @Thalhammer How do you feel about 0.8.0 being C++17?

Not sure what C++17 would give us except for pissing of everyone stuck on C++11. The only newer standards feature I am looking forward to is C++20's concepts (to simplify the traits checks) but apart from that not sure if theres a reason to switch.
Any particular reason why you'd wanna switch to C++17 ?

**Review by Thalhammer — APPROVED** [review]
We might need to figure out a way to install gcc 4.8 on ubuntu 20.04 or higher given that ubuntu 18.04 is going to get removed in roughly 2 months. I think it should be possible to do so by replacing the sources.list with the xenial one and then `apt update && apt install gcc`. Either that or use the [container](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontainer) key to use a docker container with ubuntu-18.04.

**Comment by prince-chrismc** [comment]
C++ 14 has `detected`,  decltype auto, generic lambda...
I also want template variables to try wide string support.

From 17 better auto rules, has included (this pr), conexpr lambda, fall through, deduction rules, void_t, more type traits

I know people are stuck but they are already will to make that compromise of that getting updates. But other are being limited. 

I'd be willing to bump to c++20 😆

**Comment by prince-chrismc** [comment]
The docker solution is definitely viable but just costs CI time which bothers no one

**Pull request merged**
