### PR TITLE
📦 List available package managers

### PR DESCRIPTION
**Pull request by prince-chrismc**
and fix the ugly looking badge for openssl =D 

0.5.1 ➡️ https://github.com/microsoft/vcpkg/pull/19618 https://github.com/conan-io/conan-center-index/pull/6893

### CODE REVIEW

**Comment by Thalhammer** [comment]
We also need to update the jwt.io website with the current support table.
Hunter support might be worth looking into. It is a package manager written entirely in cmake and works really well. I've used it in a couple of internal projects lately. Support should be pretty easy to integrate.

**Comment by prince-chrismc** [comment]
How do we update the jwt.io website?

**Comment by Thalhammer** [comment]
> How do we update the jwt.io website?

If I remember correctly we need to fork the website repo, update a json file and create a pull request, which is normally accepted without further questions.
Imma go ahead and do so, since I already added it back then.

**Review by Thalhammer — APPROVED** [review]
Do we want to support hunter with this commit, or with a different pr or not at all ?
Cause if we intend to, we would need to add some files and change the cmakelists a bit.

**Comment by prince-chrismc** [comment]
Separate PR since there's more modifications

**Pull request merged**
