### PR TITLE
Add using namespace jwt to unit tests

### PR DESCRIPTION
**Pull request by sjanel**
All is in the title. No other change in this PR.

### CODE REVIEW

**Comment by Thalhammer** [comment]
Ok, but what's the benefit of doing this ?
The tests aren't supposed to be included in other programs, so name clashes shouldn't be an issue.

**Comment by sjanel** [comment]
Benefits are readability, and removal of all prefixes of symbols accessed in jwt (removal of `jwt::`).

**Comment by prince-chrismc** [comment]
> Benefits are readability, and removal of all prefixes of symbols accessed in jwt (removal of `jwt::`).

Why not just stick a `using namespace` at the top?

This seems very stylized and adds a lot of diff, why are you looking at the symbols of the test code? You are never going to link against it.

**Comment by sjanel** [comment]
I don't have a strong opinion on this subject. Putting a top using namespace is fine for me.

**Comment by prince-chrismc** [comment]
Thanks a ton for this suggestion, since we seem to be agreed this is not a "functional" improvement and we have split or indifferent opinions... I am going to side of the side of caution and mark this as closed.

I really appreciate you brining in new ideas, please keep them coming! 🚀

**Pull request closed without merging**
